// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hF4x255OzfaoERBq3OINGHeH2pH0_Ho',
    appId: '1:356254849361:web:7e53aae3c9a208e0be5b70',
    messagingSenderId: '356254849361',
    projectId: 'ecosight-79869',
    authDomain: 'ecosight-79869.firebaseapp.com',
    storageBucket: 'ecosight-79869.firebasestorage.app',
    measurementId: 'G-LYQTVW2ZRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iqAJa1-g5bGjrBWLS1QbOiihkrQvpuY',
    appId: '1:356254849361:android:2fbd9cd0527e8872be5b70',
    messagingSenderId: '356254849361',
    projectId: 'ecosight-79869',
    storageBucket: 'ecosight-79869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRp5_9TCx6ypJeP3GtY2KV8-d6vQG6vk',
    appId: '1:356254849361:ios:c6f0627c2b1542b7be5b70',
    messagingSenderId: '356254849361',
    projectId: 'ecosight-79869',
    storageBucket: 'ecosight-79869.firebasestorage.app',
    iosBundleId: 'com.example.togethersoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRp5_9TCx6ypJeP3GtY2KV8-d6vQG6vk',
    appId: '1:356254849361:ios:c6f0627c2b1542b7be5b70',
    messagingSenderId: '356254849361',
    projectId: 'ecosight-79869',
    storageBucket: 'ecosight-79869.firebasestorage.app',
    iosBundleId: 'com.example.togethersoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7hF4x255OzfaoERBq3OINGHeH2pH0_Ho',
    appId: '1:356254849361:web:6818fcddfeff0ff9be5b70',
    messagingSenderId: '356254849361',
    projectId: 'ecosight-79869',
    authDomain: 'ecosight-79869.firebaseapp.com',
    storageBucket: 'ecosight-79869.firebasestorage.app',
    measurementId: 'G-ZDXRE9ZVQJ',
  );
}
